### ISSUE TITLE
Prepatch: bad argument #1 to '?' (Usage: local spellInfo = C_Spell.GetSpellInfo(spellIdentifier))

### ISSUE THREAD

**Issue by Tovrin** [Dicebar/Raven#78]
78x bad argument #1 to '?' (Usage: local spellInfo = C_Spell.GetSpellInfo(spellIdentifier))
[string "=[C]"]: in function `GetSpellInfo'
[string "@Raven/Shims.lua"]:88: in function `GetSpellInfo'
[string "@Raven/Profile.lua"]:358: in function `SetCooldownDefaults'
[string "@Raven/Main.lua"]:1026: in function `?'
[string "@Altoholic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...lic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Altoholic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...lic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Altoholic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Bears_Audio_Switcher/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...rs_Audio_Switcher/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = "bad argument #1 to '?' (Usage: local spellInfo = C_Spell.GetSpellInfo(spellIdentifier))"

**Comment by Andf** [comment]
Hello! I'm having the same issue, I think.
I appreciated Altoholic is mentioned but I don't have it enable :(


`9x bad argument #1 to '?' (Usage: local spellInfo = C_Spell.GetSpellInfo(spellIdentifier))
[string "=[C]"]: in function `GetSpellInfo'
[string "@Raven/Shims.lua"]:88: in function `GetSpellInfo'
[string "@Raven/Main.lua"]:1094: in function <Raven/Main.lua:1065>
[string "@Raven/Main.lua"]:1274: in function `Update'
[string "@Raven/Main.lua"]:953: in function <Raven/Main.lua:949>
[string "@Raven/Main.lua"]:984: in function `?'
[string "@Altoholic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...lic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Altoholic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...lic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Altoholic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Bartender4/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Bartender4/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = "bad argument #1 to '?' (Usage: local spellInfo = C_Spell.GetSpellInfo(spellIdentifier))"`

**Comment by Dicebar** [comment]
This is a curious problem... I _thought_ I fixed this bug with r663, but it is part of the code that was affected by the pre-patch...

A few questions:
- Can you confirm that you're using r663?
- What class are you playing?
- Which version of the game are you playing? Retail? Classic? Anything else?

_/edit: r663, not r623._

**Comment by Dicebar** [comment]
By @FvonY:
> There is something wonky about the call to SHIM:GetSpellInfo in GetWeaponBuffs in Main.lua around line 1589. This might be related, since it works if i comment out the call there.
> 
> E: Yep. This seems to break characters with Weapon Buffs like shaman.
> E2: The error pops up as soon as you use a weapon buff(tested with Flametongue Weapon)
> 16x bad argument #1 to '?' (Usage: local spellInfo = C_Spell.GetSpellInfo(spellIdentifier)) [string "=[C]"]: in function GetSpellInfo'
> [string "@Raven/Shims.lua"]:88: in function GetSpellInfo' [string "@Raven/Main.lua"]:1589: in function <Raven/Main.lua:1558> [string "@Raven/Main.lua"]:1987: in function UpdateAuras'
> [string "@Raven/Main.lua"]:1282: in function Update' [string "@Raven/Main.lua"]:953: in function <Raven/Main.lua:949> [string "@Raven/Main.lua"]:984: in function ?'
> [string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
> [string "=[C]"]: ?
> [string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
> [string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
> [string "@Bartender4/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Bartender4/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
> 
> Locals:
> (*temporary) = "bad argument https://github.com/Dicebar/Raven/issues/1 to '?' (Usage: local spellInfo = C_Spell.GetSpellInfo(spellIdentifier))"`

**Comment by Dicebar** [comment]
@FvonY: Knowing that this is related to weapon buffs helps a lot, thank you. I'll investigate!

**Comment by FvonY** [comment]
> By @FvonY:
> 
> > There is something wonky about the call to SHIM:GetSpellInfo in GetWeaponBuffs in Main.lua around line 1589. This might be related, since it works if i comment out the call there.

Sorry, posted in the wrong issue. I deleted and redownloaded Raven r664 (and added Raven_Options from a recent version). The error persists. In my case none of the arguments to GetSpellInfo exist within the scope(spellId or spellName or spellLink). Also, none of the results would be used within the scope anyway. Main.lua line 1588.

**Comment by Andf** [comment]
I have just deleted Raven and re-installed it, still receiving this error with addon not loading:

`14x bad argument #1 to '?' (Usage: local spellInfo = C_Spell.GetSpellInfo(spellIdentifier))
[string "=[C]"]: in function `GetSpellInfo'
[string "@Raven/Shims.lua"]:88: in function `GetSpellInfo'
[string "@Raven/Main.lua"]:1094: in function <Raven/Main.lua:1065>
[string "@Raven/Main.lua"]:1274: in function `Update'
[string "@Raven/Main.lua"]:953: in function <Raven/Main.lua:949>
[string "@Raven/Main.lua"]:984: in function `?'
[string "@Altoholic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...lic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Altoholic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...lic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Altoholic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Bartender4/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Bartender4/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = "bad argument #1 to '?' (Usage: local spellInfo = C_Spell.GetSpellInfo(spellIdentifier))"`

Raven TOC file on my PC is:

## Interface: 110000
## Title: Raven
## Notes: Monitors buffs, debuffs and cooldowns and provides timer bars and icons plus helpful notifications
## Author: Tomber, Dicebar, Dorana
## Version: r664
## DefaultState: enabled
## OptionalDependencies: Masque
## SavedVariables: RavenDB

## X-WoWI-ID: 18242

#@no-lib-strip@
embeds.xml
#@end-no-lib-strip@

Localizations\enUS.lua
Localizations\ruRU.lua

Main.lua
Profile.lua
Conditions.lua
Values.lua
Bars.lua
Cancel.lua
Nest.lua
Shims.lua

Presets\DeathKnight.lua
Presets\DemonHunter.lua
Presets\Druid.lua
Presets\Evoker.lua
Presets\Hunter.lua
Presets\Mage.lua
Presets\Monk.lua
Presets\Paladin.lua
Presets\Priest.lua
Presets\Rogue.lua
Presets\Shaman.lua
Presets\Warlock.lua
Presets\Warrior.lua
Presets\General.lua

**Comment by Andf** [comment]
BTW, is it intended that the file downloaded is missing Raven Options folder?

**Comment by Dicebar** [comment]
> BTW, is it intended that the file downloaded is missing Raven Options folder?

Very much not so, it seems to be a bug with BigWigs' packager. I filed [an issue](https://github.com/BigWigsMods/packager/issues/172) with them, hoping for a quick resolution.

**Comment by Dicebar** [comment]
Regarding the weapon enchant issue; I'm hoping this is resolved with r665 which is coming out now.

It seems that the line highlighted by @FvonY was dead code that, until TWW, didn't cause fatal errors, so I removed the line of code.

**Comment by Tovrin** [comment]
Thanks.  

Sorry I couldn't answer your question in time.  AEST timezone.  Only just got out of bed now.
